In [1]:
import pandas as pd
import os

# web crawling packages
import requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

from lxml import html
import urllib.request
from html_table_parser.parser import HTMLTableParser
from pprint import pprint

In [2]:
# Opens a website and read its
# binary contents (HTTP Response Body)
def url_get_contents(url):

    # Opens a website and read its
    # binary contents (HTTP Response Body)

    #making request to the website
    req = urllib.request.Request(url=url)
    f = urllib.request.urlopen(req)

    #reading contents of the website
    return f.read()

In [5]:
# defining the html contents of a URL.
xhtml = url_get_contents('https://www.espn.com/college-football/matchup/_/gameId/401525469').decode('utf-8')

# Defining the HTMLTableParser object
p = HTMLTableParser()

# feeding the html contents in the
# HTMLTableParser object
p.feed(xhtml)

# Now finally obtaining the data of
# the table required
#pprint(p.tables[1])

df_testing = pd.DataFrame(p.tables[1])
column_list = list(df_testing[0].values)

away = pd.DataFrame(df_testing[1]).T
away.columns = column_list
away = away.reset_index()
# away = away.drop(columns = ['index', 'Matchup'])
away = away.drop(columns = ['index'])
#away.drop(away.columns[[13]], axis=1, inplace=True)
away = away.rename(columns = {'1st Downs': 'first_downs_away',
                            # 'Passing 1st downs': 'first_downs_passing_away',
                            # 'Rushing 1st downs': 'first_downs_rushing_away', 
                            # '1st downs from penalties': 'first_down_by_penalty_away', 
                            '3rd down efficiency': 'third_down_away', 
                            '4th down efficiency': 'fourth_down_away', 
                            # 'Total Plays': 'total_plays_away', 
                            'Total Yards': 'total_yards_away', 
                            # 'Total Drives': 'total_drives_away', 
                            # 'Yards per Play': 'yards_per_play_away', 
                            'Passing': 'passing_away', 
                            'Comp-Att': 'comp_att_away', 
                            'Yards per pass': 'yards_per_pass_away',  
                            # 'Sacks-Yards Lost': 'sack_yards_lost_away', 
                            'Rushing': 'rushing_away', 
                            'Rushing Attempts': 'rushing_att_away', 
                            'Yards per rush': 'yards_per_rush_away', 
                            # 'Red Zone (Made-Att)': 'red_zone_att_away', 
                            'Penalties': 'penalty_away', 
                            'Turnovers': 'turnovers_away', 
                            'Interceptions thrown': 'int_thrown_away',
                            'Fumbles lost': 'fumbles_lost_away',
                            # 'Rushing 1st downs': 'first_down_rushing_away', 
                            # 'Defensive / Special Teams TDs': 'defensive_td_away', 
                            'Possession': 'possession_away'})

home = pd.DataFrame(df_testing[2]).T
home.columns = column_list
home = home.reset_index()
# home = home.drop(columns = ['index', 'Matchup'])
home = home.drop(columns = ['index'])
#home.drop(home.columns[[13]], axis=1, inplace=True)
home = home.rename(columns = {'1st Downs': 'first_downs_home',
                            # 'Passing 1st downs': 'first_downs_passing_home',
                            # 'Rushing 1st downs': 'first_downs_rushing_home', 
                            # '1st downs from penalties': 'first_down_by_penalty_home', 
                            '3rd down efficiency': 'third_down_home', 
                            '4th down efficiency': 'fourth_down_home', 
                            # 'Total Plays': 'total_plays_home', 
                            'Total Yards': 'total_yards_home', 
                            # 'Total Drives': 'total_drives_home', 
                            # 'Yards per Play': 'yards_per_play_home', 
                            'Passing': 'passing_home', 
                            'Comp-Att': 'comp_att_home', 
                            'Yards per pass': 'yards_per_pass_home',  
                            # 'Sacks-Yards Lost': 'sack_yards_lost_home', 
                            'Rushing': 'rushing_home', 
                            'Rushing Attempts': 'rushing_att_home', 
                            'Yards per rush': 'yards_per_rush_home', 
                            # 'Red Zone (Made-Att)': 'red_zone_att_home', 
                            'Penalties': 'penalty_home', 
                            'Turnovers': 'turnovers_home', 
                            'Interceptions thrown': 'int_thrown_home',
                            'Fumbles lost': 'fumbles_lost_home',
                            # 'Rushing 1st downs': 'first_down_rushing_home', 
                            # 'Defensive / Special Teams TDs': 'defensive_td_home', 
                            'Possession': 'possession_home'})

game_stat_temp = pd.concat([away, home], axis=1)
game_stat_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0                        1 non-null      object
 1   first_downs_away     1 non-null      object
 2   third_down_away      1 non-null      object
 3   fourth_down_away     1 non-null      object
 4   total_yards_away     1 non-null      object
 5   passing_away         1 non-null      object
 6   comp_att_away        1 non-null      object
 7   yards_per_pass_away  1 non-null      object
 8   int_thrown_away      1 non-null      object
 9   rushing_away         1 non-null      object
 10  rushing_att_away     1 non-null      object
 11  yards_per_rush_away  1 non-null      object
 12  penalty_away         1 non-null      object
 13  turnovers_away       1 non-null      object
 14  fumbles_lost_away    1 non-null      object
 15  int_thrown_away      1 non-null      object
 16  possession_away      1 non-null      object
 17                       1 non-null      object
 18  first_downs_home     1 non-null      object
 19  third_down_home      1 non-null      object
 20  fourth_down_home     1 non-null      object
 21  total_yards_home     1 non-null      object
 22  passing_home         1 non-null      object
 23  comp_att_home        1 non-null      object
 24  yards_per_pass_home  1 non-null      object
 25  int_thrown_home      1 non-null      object
 26  rushing_home         1 non-null      object
 27  rushing_att_home     1 non-null      object
 28  yards_per_rush_home  1 non-null      object
 29  penalty_home         1 non-null      object
 30  turnovers_home       1 non-null      object
 31  fumbles_lost_home    1 non-null      object
 32  int_thrown_home      1 non-null      object
 33  possession_home      1 non-null      object
dtypes: object(34)
memory usage: 400.0+ bytes

In [6]:
game_stat_temp

,,first_downs_away,third_down_away,fourth_down_away,total_yards_away,passing_away,comp_att_away,yards_per_pass_away,int_thrown_away,rushing_away,...,yards_per_pass_home,int_thrown_home,rushing_home,rushing_att_home,yards_per_rush_home,penalty_home,turnovers_home,fumbles_lost_home,int_thrown_home,possession_home
0,,8,3-14,1-1,166,72,8-22,3.3,1,94,...,10.2,2,344,44,7.8,7-44,2,0,2,31:07

## more testing with finding the teams for each game

In [18]:
driver_service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=driver_service)
# driver.get('https://www.espn.com/college-football/scoreboard/_/week/14/year/2023/seasontype/2')
driver.get('https://www.espn.com/college-football/scoreboard/_/week/2/year/2023/seasontype/2')

away_team_names = driver.find_elements(By.CSS_SELECTOR, 'li.ScoreboardScoreCell__Item--away')

In [25]:
print(len(away_team_names))

keep_list = []

for i in away_team_names:
    print(i.text.split('\n')[0])

    # test if i.text.split('\n')[0] is a number, if so keep that and name this rank_var
    if i.text.split('\n')[0].isdigit():
        rank_var = i.text.split('\n')[0]
        team_name_var = i.text.split('\n')[1]
        record_var = i.text.split('\n')[2]
    else:
        rank_var = ''
        team_name_var = i.text.split('\n')[0]
        record_var = i.text.split('\n')[1]

    keep_list.append([rank_var, team_name_var, record_var])

23
Ball State
UNLV
11
Southern Miss
Youngstown State
Stanford
Delaware
Tulsa
Austin Peay
10
12
13
Grambling
Troy
UC Davis
Appalachian State
SMU
19
20
Lafayette
Nebraska
23
Charleston Southern

In [27]:
pd.DataFrame(keep_list)

     0                    1               2
0                Ball State    (0-20-2Away)
1                      UNLV    (1-10-1Away)
2   11                Texas    (2-01-0Away)
3             Southern Miss    (1-10-1Away)
4          Youngstown State    (1-10-1Away)
5                  Stanford  (1-10-1Pac-12)
6                  Delaware    (1-11-1Away)
7                     Tulsa    (1-10-1Away)
8               Austin Peay    (0-20-2Away)
9   10           Notre Dame    (3-01-0Away)
10  12                 Utah    (2-01-0Away)
11  13               Oregon          (12-2)
12                Grambling    (0-20-1Away)
13                     Troy    (1-10-1Away)
14                 UC Davis    (1-11-1Away)
15        Appalachian State    (1-10-1Away)
16                      SMU    (1-10-1Away)
17  19            Wisconsin    (1-10-1Away)
18  20             Ole Miss    (2-01-0Away)
19                Lafayette    (1-11-1Away)
20                 Nebraska    (0-20-2Away)
21  23            Texas A&M    (1-10-1Away)
22      Charleston Southern    (1-10-1Away)